---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: sapphire-store-2023-june-x1y2z3
spec:
  forProvider:
    acl: private
    locationConstraint: us-east-1
    notificationConfiguration:
      queueConfigurations:
        - events:
            - s3:ObjectCreated:*
            - s3:ObjectRemoved:*
          # queueArn: (is resolved by the controller)
          queueArnSelector:
            matchLabels:
              stage: example
  providerConfigRef:
    name: default
