---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: sapphire-store-2023-june-x1y2z3
spec:
  writeConnectionSecretToRef:
    name: my-bucket-connection-details
    namespace: upbound-system
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-east-1
  providerConfigRef:
    name: default
