---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: nebula-backup-2023-june-s7t8u9
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-east-1
  providerConfigRef:
    name: default
