---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: luna-archive-2023-june-p4q5r6
spec:
  forProvider:
    objectOwnership: BucketOwnerEnforced
    locationConstraint: us-east-1
    notificationConfiguration:
      queueConfigurations:
        - events:
            - s3:ObjectCreated:*
            - s3:ObjectRemoved:*
          # queueArn: (is resolved by the controller)
          queueArnRef:
            name: my-queue
  providerConfigRef:
    name: default
