---
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: nova-vault-2023-june-i2j3k4
spec:
  forProvider:
    region: us-east-1
    delaySeconds: 4
  providerConfigRef:
    name: default
