---
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: cosmic-vault-2023-june-w0x1y2
spec:
  forProvider:
    region: us-east-1
    delaySeconds: 4
  providerConfigRef:
    name: default
